import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ChatGpt Messenger',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head />
      <body>
        <div>
          {/* SideBar */} 

          {/* CientProvider */}
        
          <div className='bg-[#343341] flex-1'>{children}</div>
        </div>
      </body>
    </html>
  )
}
