import SideBar from '@/components/SideBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ChatGpt Messenger',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
     <head />
      <body>
        <div className='flex'>
          {/* SideBar */}
        <div className='bg-[#434446] max-w-xs h-screen overflow-y-auto
        md:min-w-[20rem]'>
            <SideBar />
          </div>

          {/* CientProvider */}
        
          <div className='bg-[#282730] flex-1'>{children}</div>
        </div>
      </body>
    </html>
  )
}
